when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false
        register_error_handler: false
        options:
            environment: prod
            release: '%env(default::SENTRY_RELEASE)%'
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'

    monolog:
        handlers:
            sentry:
                type: service
                id: Sentry\Monolog\Handler

    services:
        Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $level: !php/const Monolog\Logger::ERROR
                $fillExtraContext: true