<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315111924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_encrypted VARCHAR(255) NOT NULL, is_being_trained BOOLEAN DEFAULT false NOT NULL, telegram_user_id BIGINT NOT NULL, is_trained BOOLEAN DEFAULT false NOT NULL, target_from_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, chat_export_file_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_11F04117E3C61F9 ON bot (owner_id)');
        $this->addSql('CREATE INDEX IDX_11F041115F0DA79 ON bot (chat_export_file_id)');
        $this->addSql('CREATE TABLE chat_export_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, telegram_file_id VARCHAR(255) DEFAULT NULL, is_imported BOOLEAN DEFAULT false NOT NULL, chat_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_955CF7637E3C61F9 ON chat_export_file (owner_id)');
        $this->addSql('CREATE TABLE chat_export_upload_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, is_used BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resulted_file_id INT DEFAULT NULL, bot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_36B8933123522752 ON chat_export_upload_link (resulted_file_id)');
        $this->addSql('CREATE INDEX IDX_36B8933192C1C487 ON chat_export_upload_link (bot_id)');
        $this->addSql('CREATE TABLE chat_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, telegram_message_id BIGINT NOT NULL, from_id VARCHAR(255) NOT NULL, sender VARCHAR(255) NOT NULL, text TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reply_to_telegram_message_id BIGINT DEFAULT NULL, chat_export_file_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FAB3FC1615F0DA79 ON chat_message (chat_export_file_id)');
        $this->addSql('CREATE INDEX idx_from_id ON chat_message (chat_export_file_id, from_id)');
        $this->addSql('CREATE INDEX idx_telegram_msg_id ON chat_message (chat_export_file_id, telegram_message_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, telegram_id BIGINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE bot ADD CONSTRAINT FK_11F04117E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bot ADD CONSTRAINT FK_11F041115F0DA79 FOREIGN KEY (chat_export_file_id) REFERENCES chat_export_file (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_export_file ADD CONSTRAINT FK_955CF7637E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_export_upload_link ADD CONSTRAINT FK_36B8933123522752 FOREIGN KEY (resulted_file_id) REFERENCES chat_export_file (id)');
        $this->addSql('ALTER TABLE chat_export_upload_link ADD CONSTRAINT FK_36B8933192C1C487 FOREIGN KEY (bot_id) REFERENCES bot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_message ADD CONSTRAINT FK_FAB3FC1615F0DA79 FOREIGN KEY (chat_export_file_id) REFERENCES chat_export_file (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bot DROP CONSTRAINT FK_11F04117E3C61F9');
        $this->addSql('ALTER TABLE bot DROP CONSTRAINT FK_11F041115F0DA79');
        $this->addSql('ALTER TABLE chat_export_file DROP CONSTRAINT FK_955CF7637E3C61F9');
        $this->addSql('ALTER TABLE chat_export_upload_link DROP CONSTRAINT FK_36B8933123522752');
        $this->addSql('ALTER TABLE chat_export_upload_link DROP CONSTRAINT FK_36B8933192C1C487');
        $this->addSql('ALTER TABLE chat_message DROP CONSTRAINT FK_FAB3FC1615F0DA79');
        $this->addSql('DROP TABLE bot');
        $this->addSql('DROP TABLE chat_export_file');
        $this->addSql('DROP TABLE chat_export_upload_link');
        $this->addSql('DROP TABLE chat_message');
        $this->addSql('DROP TABLE "user"');
    }
}
