<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225131403 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chat_export_upload_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, is_used BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resulted_file_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_36B8933123522752 ON chat_export_upload_link (resulted_file_id)');
        $this->addSql('ALTER TABLE chat_export_upload_link ADD CONSTRAINT FK_36B8933123522752 FOREIGN KEY (resulted_file_id) REFERENCES chat_export_file (id)');
        $this->addSql('ALTER TABLE chat_export_file ALTER telegram_file_id DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_export_upload_link DROP CONSTRAINT FK_36B8933123522752');
        $this->addSql('DROP TABLE chat_export_upload_link');
        $this->addSql('ALTER TABLE chat_export_file ALTER telegram_file_id SET NOT NULL');
    }
}
