[program:frankenphp]
command=frankenphp run --config /etc/frankenphp/Caddyfile
user=appuser
autostart=true
autorestart=true
priority=20
stdout_logfile=/app/var/log/frankenphp.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/app/var/log/frankenphp.err
stderr_logfile_maxbytes=10MB
