[program:messenger]
command=php /app/bin/console messenger:consume async --time-limit=3600
user=appuser
numprocs=2
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
priority=30
startsecs=10
stdout_logfile=/app/var/log/messenger.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/app/var/log/messenger.err
stderr_logfile_maxbytes=10MB
