[program:postgres]
command=/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/data
user=postgres
autostart=true
autorestart=true
priority=10
stdout_logfile=/app/var/log/postgres.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/app/var/log/postgres.err
stderr_logfile_maxbytes=5MB
