[program:redis]
command=redis-server --appendonly yes --dir /var/lib/redis
user=redis
autostart=true
autorestart=true
priority=10
stdout_logfile=/app/var/log/redis.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/app/var/log/redis.err
stderr_logfile_maxbytes=5MB
